/*
 * Copyright (C) 2017 julio
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bliburu;

import java.util.Date;
import javax.swing.JButton;

/**
 *
 * @author julio
 */
public class Ajustes extends javax.swing.JFrame {

    Biblioteca biblioteca;
    boolean ajustando;
    
    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
        ajustando=false;
    }

    public void setBiblioteca(Biblioteca biblioteca){
        this.biblioteca = biblioteca;
    }
    
    public void refrescarInfo(){
        if(ajustando){
            
            jToggleButtonAjustes.setText("Aplicar Cambios");
            
            jSpinnerDiasLibros.setValue(biblioteca.getAdministrador().getParametrizador().getDiasPrestamoLibro());
            jSpinnerDiasRevistas.setValue(biblioteca.getAdministrador().getParametrizador().getDiasPrestamoRevista());
            jSpinnerFecha.setValue(biblioteca.getAdministrador().getParametrizador().getFechaDelSistema());
            
            jLabelAjustesFecha.setVisible(false);
            jLabelDiasPrestamoLibro.setVisible(false);
            jLabelDiasPrestamoRevista.setVisible(false);
            jSpinnerDiasLibros.setVisible(true);
            jSpinnerDiasRevistas.setVisible(true);
            jSpinnerFecha.setVisible(true);
            
        }else{
            
            jToggleButtonAjustes.setText("Ajustar Parámetros");
            
            jLabelAjustesFecha.setText(biblioteca.getAdministrador().getParametrizador().getFechaDelSistema().toString());
            jLabelDiasPrestamoLibro.setText(Integer.toString(biblioteca.getAdministrador().getParametrizador().getDiasPrestamoLibro()));
            jLabelDiasPrestamoRevista.setText(Integer.toString(biblioteca.getAdministrador().getParametrizador().getDiasPrestamoRevista()));
            
            jLabelAjustesFecha.setVisible(true);
            jLabelDiasPrestamoLibro.setVisible(true);
            jLabelDiasPrestamoRevista.setVisible(true);
            jSpinnerDiasLibros.setVisible(false);
            jSpinnerDiasRevistas.setVisible(false);
            jSpinnerFecha.setVisible(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFechaLabel = new javax.swing.JLabel();
        jLabelDiasLibroLabel = new javax.swing.JLabel();
        jLabelDiasRevistaLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelAjustesFecha = new javax.swing.JLabel();
        jLabelDiasPrestamoLibro = new javax.swing.JLabel();
        jLabelDiasPrestamoRevista = new javax.swing.JLabel();
        jToggleButtonAjustes = new javax.swing.JToggleButton();
        jSpinnerFecha = new javax.swing.JSpinner();
        jSpinnerDiasLibros = new javax.swing.JSpinner();
        jSpinnerDiasRevistas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFechaLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelFechaLabel.setText("Fecha");

        jLabelDiasLibroLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelDiasLibroLabel.setText("Días de préstamo de Libros");

        jLabelDiasRevistaLabel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelDiasRevistaLabel.setText("Días de préstamo de Revistas");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("Ajustes");

        jLabelAjustesFecha.setText("jLabel1");

        jLabelDiasPrestamoLibro.setText("jLabel1");

        jLabelDiasPrestamoRevista.setText("jLabel1");

        jToggleButtonAjustes.setText("Ajustar Parámetros");
        jToggleButtonAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAjustesActionPerformed(evt);
            }
        });

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        jSpinnerDiasLibros.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerDiasRevistas.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDiasPrestamoRevista)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerDiasRevistas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                .addComponent(jToggleButtonAjustes))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAjustesFecha)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelFechaLabel)
                                    .addComponent(jLabelDiasLibroLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDiasPrestamoLibro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerDiasLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelDiasRevistaLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(jLabelFechaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAjustesFecha)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabelDiasLibroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDiasPrestamoLibro)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelDiasRevistaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiasPrestamoRevista)
                            .addComponent(jToggleButtonAjustes)
                            .addComponent(jSpinnerDiasRevistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSpinnerDiasLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAjustesActionPerformed
        if(ajustando){
            ajustando=false;
            
            biblioteca.getAdministrador().getParametrizador().setFechaDelSistema((Date) jSpinnerFecha.getValue());
            biblioteca.getAdministrador().getParametrizador().setDiasPrestamoLibro((int) jSpinnerDiasLibros.getValue());
            biblioteca.getAdministrador().getParametrizador().setDiasPrestamoRevista((int) jSpinnerDiasRevistas.getValue());
            
            refrescarInfo();
        }else{
            ajustando=true;
            refrescarInfo();
        }
        
    }//GEN-LAST:event_jToggleButtonAjustesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAjustesFecha;
    private javax.swing.JLabel jLabelDiasLibroLabel;
    private javax.swing.JLabel jLabelDiasPrestamoLibro;
    private javax.swing.JLabel jLabelDiasPrestamoRevista;
    private javax.swing.JLabel jLabelDiasRevistaLabel;
    private javax.swing.JLabel jLabelFechaLabel;
    private javax.swing.JSpinner jSpinnerDiasLibros;
    private javax.swing.JSpinner jSpinnerDiasRevistas;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JToggleButton jToggleButtonAjustes;
    // End of variables declaration//GEN-END:variables
}
