/*
 * Copyright (C) 2017 JOAQUIN
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bliburu;

import java.awt.GridLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author JOAQUIN
 */
public class consultaPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form consultaPrestamos
     */
    Administrador admi;
    private List<Prestamo> listaPrestamos;
    Cliente cliente;
    private Date fechaActualDeSistema;
    private Date fechaDevolucionLibros;
    private Date fechaDevolucionRevistas;
    
    public consultaPrestamos() {
        initComponents();
    }
    public consultaPrestamos(Administrador admin){
        this.admi=admin;
        this.listaPrestamos = admi.getListaPrestamos();
        recorrerListaPrestamos();
    }
    
    public void recorrerListaPrestamos(){
        int contador = 0;
        while(contador < listaPrestamos.size()){
           cliente = listaPrestamos.get(contador).getCliente();
           fechaActualDeSistema = listaPrestamos.get(contador).getFecha();
           fechaDevolucionLibros = listaPrestamos.get(contador).getFechaDevolucionLibros();
           fechaDevolucionRevistas = listaPrestamos.get(contador).getFechaDevolucionRevistas();
           System.out.println("Cliente: "+cliente);
           System.out.println("Fecha de devolucion: "+fechaDevolucionLibros);
           recorrerRecursosLiterariosPrestados(contador);
           contador++;
        }
    }
    public void recorrerRecursosLiterariosPrestados(int indice){
        int dimension = listaPrestamos.get(indice).getProductosPrestados().size();
        for (int x = 0;x < dimension;x++){
            String id = listaPrestamos.get(x).getProductosPrestados().get(x).getId();
            String nombre = listaPrestamos.get(x).getProductosPrestados().get(x).getNombre();
            System.out.println(id+":"+nombre);
        }

    }
 
    
    public void refrescarPanelPrestamos(){
        JLabel Identificador = new javax.swing.JLabel("IDENTIFICADOR");
        JLabel nombre = new javax.swing.JLabel("NOMBRE");
        JLabel fechaSolicitud = new javax.swing.JLabel("FECHA-SOLICITUD");
        JLabel Cliente = new javax.swing.JLabel("CLIENTE");
        JLabel fechaDevolucion = new javax.swing.JLabel("FECHA-DEVOLUCIÓN");
        //JButton multas = new javax.swing.JButton("Consultar Multas");
        panelConsultaPrestamos.setLayout(new GridLayout(0,5,20,20));
        panelConsultaPrestamos.add(Identificador);
        panelConsultaPrestamos.add(nombre);
        panelConsultaPrestamos.add(fechaSolicitud);
        panelConsultaPrestamos.add(Cliente);
        panelConsultaPrestamos.add(fechaDevolucion);
        //panelConsultaPrestamos.add(multas);
        panelConsultaPrestamos.revalidate();
        panelConsultaPrestamos.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerBliburu = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelConsultaPrestamos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147, 2147));

        bannerBliburu.setBackground(new java.awt.Color(125, 164, 202));
        bannerBliburu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libros", "Revistas" }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Recurso Literario:");

        jLabel2.setText("IDENTIFICADOR");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("FECHA-SOLICITUD");

        jLabel5.setText("CLIENTE");

        jLabel6.setText("FECHA-DEVOLUCIÓN");

        javax.swing.GroupLayout bannerBliburuLayout = new javax.swing.GroupLayout(bannerBliburu);
        bannerBliburu.setLayout(bannerBliburuLayout);
        bannerBliburuLayout.setHorizontalGroup(
            bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerBliburuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bannerBliburuLayout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bannerBliburuLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20))))
        );
        bannerBliburuLayout.setVerticalGroup(
            bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerBliburuLayout.createSequentialGroup()
                .addGroup(bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bannerBliburuLayout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerBliburuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)))
                .addGroup(bannerBliburuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout panelConsultaPrestamosLayout = new javax.swing.GroupLayout(panelConsultaPrestamos);
        panelConsultaPrestamos.setLayout(panelConsultaPrestamosLayout);
        panelConsultaPrestamosLayout.setHorizontalGroup(
            panelConsultaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        panelConsultaPrestamosLayout.setVerticalGroup(
            panelConsultaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelConsultaPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(bannerBliburu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bannerBliburu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerBliburu;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsultaPrestamos;
    // End of variables declaration//GEN-END:variables
}
