/*
 * Copyright (C) 2017 Bliburu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bliburu;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Sánchez Jiménez (jsnchzjmnz)
 * @version 0.1
 */
public class GUI extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * Asigna la biblioteca instanciada al GUI
     * @param biblioteca biblioteca que se asignará al GUI
     */
    public void setBiblioteca(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserCargaRecursosLiterarios = new javax.swing.JFileChooser();
        jTab = new javax.swing.JTabbedPane();
        jPanelLiteratura = new javax.swing.JPanel();
        jPanelRecursosLiterarios = new javax.swing.JPanel();
        jScrollPaneFiltro = new javax.swing.JScrollPane();
        jListRecursosLiterarios = new javax.swing.JList<String>();
        jLabelRecursosLiterariosLabel = new javax.swing.JLabel();
        jPanelRecursoLiterarioFiltro = new javax.swing.JPanel();
        jLabelRecursosLiterariosFiltroLabel = new javax.swing.JLabel();
        jCheckBoxFiltroLibro = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevista = new javax.swing.JCheckBox();
        jComboBoxFiltroTipoLibro = new javax.swing.JComboBox<String>();
        jCheckBoxFiltroLibrosDisponibles = new javax.swing.JCheckBox();
        jCheckBoxFiltroLibrosPrestados = new javax.swing.JCheckBox();
        jCheckBoxFiltroTodo = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasDisponibles = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasPrestadas = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasVendidas = new javax.swing.JCheckBox();
        jLabelRegistroFiltroTipoLibro = new javax.swing.JLabel();
        jComboBoxFiltroRevistaTipo = new javax.swing.JComboBox<String>();
        jLabelRegistroTipoRevista = new javax.swing.JLabel();
        jPanelRegistroRevistasLabel = new javax.swing.JPanel();
        jLabelRegistroRevistaLabel = new javax.swing.JLabel();
        jLabelRegistroRevistaNombre = new javax.swing.JLabel();
        jLabelRegistroRevistaNumero = new javax.swing.JLabel();
        jLabelRegistroRevistaAnio = new javax.swing.JLabel();
        jLabelRegistroRevistaCosto = new javax.swing.JLabel();
        jComboBoxRegistroRevistaTipo = new javax.swing.JComboBox<String>();
        jTextFieldRegistroRevistaNombre = new javax.swing.JTextField();
        jButtonRegistroRevista = new javax.swing.JButton();
        jSpinnerAnioRevista = new javax.swing.JSpinner();
        jSpinnerRegistroRevistaNumero = new javax.swing.JSpinner();
        jSpinnerRegistroRevistaCosto = new javax.swing.JSpinner();
        jLabelRegistroRevistasTipo = new javax.swing.JLabel();
        jPanelRegistroLibros = new javax.swing.JPanel();
        jLabelRegistroLibrosTitle = new javax.swing.JLabel();
        jTextFieldRegistroLibroNombre = new javax.swing.JTextField();
        jTextFieldRegistroLibroAutor = new javax.swing.JTextField();
        jTextFieldRegistroLibroEditorial = new javax.swing.JTextField();
        jComboBoxTipoLibro = new javax.swing.JComboBox<String>();
        jLabelRegistroLibroNombre = new javax.swing.JLabel();
        jLabelRegistroLibroAutor = new javax.swing.JLabel();
        jLabelRegistroLibroEditorial = new javax.swing.JLabel();
        jLabelRegistroLibroAnio = new javax.swing.JLabel();
        jButtonRegistroLibro = new javax.swing.JButton();
        jSpinnerRegistroLibroAnio = new javax.swing.JSpinner();
        jLabelRegistroLibroTipo = new javax.swing.JLabel();
        jPanelPrestamos = new javax.swing.JPanel();
        jPanelVentas = new javax.swing.JPanel();
        jPanelClientes = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        labelCorreoCliente = new javax.swing.JLabel();
        labelCedulaCliente = new javax.swing.JLabel();
        labelTelefonoCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        txtErrorEmail = new javax.swing.JLabel();
        txtErrorTelefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        jPanelMultas = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemImportarLiteratura = new javax.swing.JMenuItem();
        jSeparatorFiltro = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuHerramientas = new javax.swing.JMenu();
        jMenuItemAjustes = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(170, 104, 69));
        setResizable(false);

        jTab.setBackground(new java.awt.Color(232, 232, 232));
        jTab.setForeground(new java.awt.Color(88, 68, 49));
        jTab.setFont(new java.awt.Font("Khmer OS System", 1, 14)); // NOI18N

        jPanelLiteratura.setBackground(new java.awt.Color(232, 232, 232));

        jListRecursosLiterarios.setBackground(new java.awt.Color(232, 232, 232));
        jListRecursosLiterarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));
        jListRecursosLiterarios.setSelectionBackground(new java.awt.Color(125, 164, 203));
        jListRecursosLiterarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListRecursosLiterariosMouseClicked(evt);
            }
        });
        jScrollPaneFiltro.setViewportView(jListRecursosLiterarios);

        jLabelRecursosLiterariosLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabelRecursosLiterariosLabel.setForeground(new java.awt.Color(88, 68, 49));
        jLabelRecursosLiterariosLabel.setText("Recursos Literarios");

        jPanelRecursoLiterarioFiltro.setBackground(new java.awt.Color(125, 164, 203));
        jPanelRecursoLiterarioFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));

        jLabelRecursosLiterariosFiltroLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelRecursosLiterariosFiltroLabel.setForeground(new java.awt.Color(88, 68, 49));
        jLabelRecursosLiterariosFiltroLabel.setText("Filtros de Búsqueda");

        jCheckBoxFiltroLibro.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibro.setText("Libros");
        jCheckBoxFiltroLibro.setEnabled(false);
        jCheckBoxFiltroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibroActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevista.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevista.setText("Revistas");
        jCheckBoxFiltroRevista.setEnabled(false);
        jCheckBoxFiltroRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistaActionPerformed(evt);
            }
        });

        jComboBoxFiltroTipoLibro.setBackground(new java.awt.Color(125, 164, 203));
        jComboBoxFiltroTipoLibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Novela", "Teatro", "Poesía", "Ensayo", "Infantil" }));
        jComboBoxFiltroTipoLibro.setEnabled(false);
        jComboBoxFiltroTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroTipoLibroActionPerformed(evt);
            }
        });

        jCheckBoxFiltroLibrosDisponibles.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibrosDisponibles.setText("Disponibles");
        jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
        jCheckBoxFiltroLibrosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibrosDisponiblesActionPerformed(evt);
            }
        });

        jCheckBoxFiltroLibrosPrestados.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibrosPrestados.setText("Prestados");
        jCheckBoxFiltroLibrosPrestados.setEnabled(false);
        jCheckBoxFiltroLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibrosPrestadosActionPerformed(evt);
            }
        });

        jCheckBoxFiltroTodo.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroTodo.setSelected(true);
        jCheckBoxFiltroTodo.setText("Mostrar Todo");
        jCheckBoxFiltroTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroTodoActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasDisponibles.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasDisponibles.setText("Disponible");
        jCheckBoxFiltroRevistasDisponibles.setEnabled(false);
        jCheckBoxFiltroRevistasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasDisponiblesActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasPrestadas.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasPrestadas.setText("Prestado");
        jCheckBoxFiltroRevistasPrestadas.setEnabled(false);
        jCheckBoxFiltroRevistasPrestadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasPrestadasActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasVendidas.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasVendidas.setText("Vendido");
        jCheckBoxFiltroRevistasVendidas.setEnabled(false);
        jCheckBoxFiltroRevistasVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasVendidasActionPerformed(evt);
            }
        });

        jLabelRegistroFiltroTipoLibro.setBackground(new java.awt.Color(125, 164, 203));
        jLabelRegistroFiltroTipoLibro.setText("Tipo");

        jComboBoxFiltroRevistaTipo.setBackground(new java.awt.Color(125, 164, 203));
        jComboBoxFiltroRevistaTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Venta", "Prestamo" }));
        jComboBoxFiltroRevistaTipo.setEnabled(false);
        jComboBoxFiltroRevistaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroRevistaTipoActionPerformed(evt);
            }
        });

        jLabelRegistroTipoRevista.setBackground(new java.awt.Color(125, 164, 203));
        jLabelRegistroTipoRevista.setText("Tipo");

        javax.swing.GroupLayout jPanelRecursoLiterarioFiltroLayout = new javax.swing.GroupLayout(jPanelRecursoLiterarioFiltro);
        jPanelRecursoLiterarioFiltro.setLayout(jPanelRecursoLiterarioFiltroLayout);
        jPanelRecursoLiterarioFiltroLayout.setHorizontalGroup(
            jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRecursosLiterariosFiltroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFiltroTodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxFiltroLibro)
                    .addComponent(jCheckBoxFiltroRevista)
                    .addGroup(jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelRegistroFiltroTipoLibro))
                    .addGroup(jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabelRegistroTipoRevista))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFiltroLibrosPrestados)
                                    .addComponent(jCheckBoxFiltroLibrosDisponibles)
                                    .addComponent(jComboBoxFiltroTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFiltroRevistasPrestadas)
                                    .addComponent(jCheckBoxFiltroRevistasDisponibles)
                                    .addComponent(jCheckBoxFiltroRevistasVendidas)))))))
        );
        jPanelRecursoLiterarioFiltroLayout.setVerticalGroup(
            jPanelRecursoLiterarioFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecursoLiterarioFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRecursosLiterariosFiltroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibrosDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibrosPrestados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegistroFiltroTipoLibro)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxFiltroTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxFiltroRevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasPrestadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasVendidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRegistroTipoRevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFiltroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanelRecursosLiterariosLayout = new javax.swing.GroupLayout(jPanelRecursosLiterarios);
        jPanelRecursosLiterarios.setLayout(jPanelRecursosLiterariosLayout);
        jPanelRecursosLiterariosLayout.setHorizontalGroup(
            jPanelRecursosLiterariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecursosLiterariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRecursoLiterarioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelRecursosLiterariosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabelRecursosLiterariosLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRecursosLiterariosLayout.setVerticalGroup(
            jPanelRecursosLiterariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecursosLiterariosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelRecursosLiterariosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRecursosLiterariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRecursoLiterarioFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneFiltro))
                .addContainerGap())
        );

        jLabelRegistroRevistaLabel.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabelRegistroRevistaLabel.setForeground(new java.awt.Color(88, 68, 49));
        jLabelRegistroRevistaLabel.setText("Registro de Revistas");

        jLabelRegistroRevistaNombre.setText("Nombre");

        jLabelRegistroRevistaNumero.setText("Número");

        jLabelRegistroRevistaAnio.setText("Año");

        jLabelRegistroRevistaCosto.setText("Costo");

        jComboBoxRegistroRevistaTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Venta", "Prestamo" }));

        jTextFieldRegistroRevistaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistroRevistaNombreActionPerformed(evt);
            }
        });

        jButtonRegistroRevista.setText("Registrar");
        jButtonRegistroRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroRevistaActionPerformed(evt);
            }
        });

        jSpinnerAnioRevista.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerAnioRevista.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerAnioRevista, "yyyy"));

        jSpinnerRegistroRevistaNumero.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerRegistroRevistaCosto.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1500.0d), null, null, Double.valueOf(1.0d)));

        jLabelRegistroRevistasTipo.setText("Tipo");

        javax.swing.GroupLayout jPanelRegistroRevistasLabelLayout = new javax.swing.GroupLayout(jPanelRegistroRevistasLabel);
        jPanelRegistroRevistasLabel.setLayout(jPanelRegistroRevistasLabelLayout);
        jPanelRegistroRevistasLabelLayout.setHorizontalGroup(
            jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                                        .addComponent(jLabelRegistroRevistaNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldRegistroRevistaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelRegistroRevistaCosto))
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                                .addComponent(jLabelRegistroRevistaNumero)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerRegistroRevistaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerRegistroRevistaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRegistroRevistaAnio)
                                    .addComponent(jLabelRegistroRevistasTipo))
                                .addGap(40, 40, 40)
                                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAnioRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                                        .addComponent(jComboBoxRegistroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRegistroRevista)
                                        .addGap(55, 55, 55))))))
                    .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelRegistroRevistaLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRegistroRevistasLabelLayout.setVerticalGroup(
            jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                .addComponent(jLabelRegistroRevistaLabel)
                .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistroRevistaNombre)
                            .addComponent(jTextFieldRegistroRevistaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistroRevistaNumero)
                            .addComponent(jSpinnerRegistroRevistaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRegistroRevistaCosto)
                            .addComponent(jSpinnerRegistroRevistaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerAnioRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistroRevistaAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroRevistasLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRegistroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistroRevistasTipo))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroRevistasLabelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRegistroRevista))))
        );

        jLabelRegistroLibrosTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabelRegistroLibrosTitle.setForeground(new java.awt.Color(88, 68, 49));
        jLabelRegistroLibrosTitle.setText("Registro de Libros");

        jTextFieldRegistroLibroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistroLibroNombreActionPerformed(evt);
            }
        });

        jComboBoxTipoLibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novela", "Teatro", "Poesía", "Ensayo", "Infantil" }));

        jLabelRegistroLibroNombre.setText("Nombre");

        jLabelRegistroLibroAutor.setText("Autor");

        jLabelRegistroLibroEditorial.setText("Editorial");

        jLabelRegistroLibroAnio.setText("Año");

        jButtonRegistroLibro.setText("Registrar");
        jButtonRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroLibroActionPerformed(evt);
            }
        });

        jSpinnerRegistroLibroAnio.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerRegistroLibroAnio.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerRegistroLibroAnio, "yyyy"));

        jLabelRegistroLibroTipo.setText("Tipo");

        javax.swing.GroupLayout jPanelRegistroLibrosLayout = new javax.swing.GroupLayout(jPanelRegistroLibros);
        jPanelRegistroLibros.setLayout(jPanelRegistroLibrosLayout);
        jPanelRegistroLibrosLayout.setHorizontalGroup(
            jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLibrosLayout.createSequentialGroup()
                                        .addComponent(jLabelRegistroLibroNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                        .addComponent(jLabelRegistroLibroAutor)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldRegistroLibroAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRegistroLibroNombre)))
                            .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRegistroLibroEditorial)
                                    .addComponent(jLabelRegistroLibroTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                        .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinnerRegistroLibroAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldRegistroLibroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 59, Short.MAX_VALUE))
                                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                        .addComponent(jComboBoxTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRegistroLibro))))))
                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelRegistroLibrosTitle))
                            .addComponent(jLabelRegistroLibroAnio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRegistroLibrosLayout.setVerticalGroup(
            jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                .addComponent(jLabelRegistroLibrosTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistroLibroNombre)
                    .addComponent(jTextFieldRegistroLibroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegistroLibroAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLibroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegistroLibroEditorial))
                .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroLibrosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegistroLibroAnio)
                            .addComponent(jSpinnerRegistroLibroAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistroLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistroLibroTipo))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLibrosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistroLibro))))
        );

        javax.swing.GroupLayout jPanelLiteraturaLayout = new javax.swing.GroupLayout(jPanelLiteratura);
        jPanelLiteratura.setLayout(jPanelLiteraturaLayout);
        jPanelLiteraturaLayout.setHorizontalGroup(
            jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLiteraturaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRegistroLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRegistroRevistasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRecursosLiterarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLiteraturaLayout.setVerticalGroup(
            jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLiteraturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLiteraturaLayout.createSequentialGroup()
                        .addComponent(jPanelRegistroLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jPanelRegistroRevistasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelRecursosLiterarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTab.addTab("Literatura", jPanelLiteratura);

        jPanelPrestamos.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelPrestamosLayout = new javax.swing.GroupLayout(jPanelPrestamos);
        jPanelPrestamos.setLayout(jPanelPrestamosLayout);
        jPanelPrestamosLayout.setHorizontalGroup(
            jPanelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelPrestamosLayout.setVerticalGroup(
            jPanelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Prestamos", jPanelPrestamos);

        jPanelVentas.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Ventas", jPanelVentas);

        jPanelClientes.setBackground(new java.awt.Color(232, 232, 232));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Agregar Cliente");

        labelNombreCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNombreCliente.setText("Nombre:");

        labelCorreoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCorreoCliente.setText("Correo electrónico:");

        labelCedulaCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCedulaCliente.setText("Cédula de Identificación:");

        labelTelefonoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTelefonoCliente.setText("Telefóno:");

        txtNombreCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtEmailCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailClienteKeyTyped(evt);
            }
        });

        txtCedulaCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTelefonoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoClienteKeyTyped(evt);
            }
        });

        btnAgregarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        txtErrorEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        txtErrorTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtErrorTelefono.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelNombreCliente)
                        .addGap(28, 28, 28)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(labelCedulaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(labelCorreoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(labelTelefonoCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(txtErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtErrorEmail)
                        .addGap(62, 62, 62)
                        .addComponent(txtErrorTelefono)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCorreoCliente)
                            .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCedulaCliente)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefonoCliente)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnAgregarCliente)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel);

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientesLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTab.addTab("Clientes", jPanelClientes);

        jPanelMultas.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelMultasLayout = new javax.swing.GroupLayout(jPanelMultas);
        jPanelMultas.setLayout(jPanelMultasLayout);
        jPanelMultasLayout.setHorizontalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelMultasLayout.setVerticalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Multas", jPanelMultas);

        jPanelHeader.setBackground(new java.awt.Color(125, 164, 202));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemImportarLiteratura.setText("Importar Literatura");
        jMenuItemImportarLiteratura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportarLiteraturaActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemImportarLiteratura);
        jMenuArchivo.add(jSeparatorFiltro);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuHerramientas.setText("Herramientas");

        jMenuItemAjustes.setText("Ajustes");
        jMenuItemAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjustesActionPerformed(evt);
            }
        });
        jMenuHerramientas.add(jMenuItemAjustes);

        jMenuBar.add(jMenuHerramientas);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaActionPerformed(evt);
            }
        });

        jMenuItemAyuda.setText("Ayuda");
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAyuda);

        jMenuItemAcerca.setText("Acerca");
        jMenuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcerca);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaActionPerformed
        Acerca acerca = new Acerca();
        acerca.setTitle("About");
        acerca.show();
    }//GEN-LAST:event_jMenuItemAcercaActionPerformed

    private void jMenuItemAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjustesActionPerformed
        Ajustes ajustes = new Ajustes();
        ajustes.setBiblioteca(biblioteca);
        ajustes.refrescarInfo();
        ajustes.show();
    }//GEN-LAST:event_jMenuItemAjustesActionPerformed

    private void jCheckBoxFiltroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibroActionPerformed
        if (jCheckBoxFiltroLibro.isSelected()) {
            jCheckBoxFiltroLibrosDisponibles.setEnabled(true);
            jCheckBoxFiltroLibrosPrestados.setEnabled(true);
            jComboBoxFiltroTipoLibro.setEnabled(true);
        }else{
            jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
            jCheckBoxFiltroLibrosPrestados.setEnabled(false);
            jComboBoxFiltroTipoLibro.setEnabled(false);
        }
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibroActionPerformed

    private void jTextFieldRegistroLibroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistroLibroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistroLibroNombreActionPerformed

    private void jTextFieldRegistroRevistaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistroRevistaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistroRevistaNombreActionPerformed

    private void jButtonRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroLibroActionPerformed

        biblioteca.getInventario().registrarLibro(jTextFieldRegistroLibroNombre.getText(), jTextFieldRegistroLibroAutor.getText(), (Date) jSpinnerRegistroLibroAnio.getModel().getValue(),jTextFieldRegistroLibroEditorial.getText(), TipoLibro.valueOf(jComboBoxTipoLibro.getModel().getSelectedItem().toString().toUpperCase()));
        refrescarjListRecursosLiterarios();
        
    }//GEN-LAST:event_jButtonRegistroLibroActionPerformed

    private void jMenuItemImportarLiteraturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportarLiteraturaActionPerformed
        int returnVal = jFileChooserCargaRecursosLiterarios.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        String ruta = jFileChooserCargaRecursosLiterarios.getSelectedFile().getAbsolutePath();
            try {
                biblioteca.getInventario().registroAutomatico(ruta);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            refrescarjListRecursosLiterarios();
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jMenuItemImportarLiteraturaActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonRegistroRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroRevistaActionPerformed
        biblioteca.getInventario().registrarRevista(jTextFieldRegistroRevistaNombre.getText(), (int) jSpinnerRegistroRevistaNumero.getModel().getValue(), (Date) jSpinnerAnioRevista.getValue(), TipoRevista.valueOf(jComboBoxRegistroRevistaTipo.getModel().getSelectedItem().toString().toUpperCase()), (double) jSpinnerRegistroRevistaCosto.getValue());
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jButtonRegistroRevistaActionPerformed

    private void jCheckBoxFiltroTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroTodoActionPerformed
        if(jCheckBoxFiltroTodo.isSelected()){
            jCheckBoxFiltroLibro.setEnabled(false);
            jCheckBoxFiltroRevista.setEnabled(false);
            jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
            jCheckBoxFiltroLibrosPrestados.setEnabled(false);
            jComboBoxFiltroTipoLibro.setEnabled(false);
            
            
        }else{
            jCheckBoxFiltroLibro.setEnabled(true);
            jCheckBoxFiltroRevista.setEnabled(true);
            if(jCheckBoxFiltroLibro.isSelected()){
                jCheckBoxFiltroLibrosDisponibles.setEnabled(true);
                jCheckBoxFiltroLibrosPrestados.setEnabled(true);
                jComboBoxFiltroTipoLibro.setEnabled(true);
            }else{
                jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
                jCheckBoxFiltroLibrosPrestados.setEnabled(false);
                jComboBoxFiltroTipoLibro.setEnabled(false);
            }
            
           
        }
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroTodoActionPerformed

    private void jCheckBoxFiltroLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibrosPrestadosActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibrosPrestadosActionPerformed

    private void jListRecursosLiterariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRecursosLiterariosMouseClicked
        
        if(jListRecursosLiterarios.getModel().getSize()>0){
 
            String id= jListRecursosLiterarios.getSelectedValue().split(" ")[0];
            int contador=0;
            boolean flag=false;
            while(contador<biblioteca.getInventario().getListaRecursosLiterarios().size() && !flag){
                if(biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains(id)){
                    flag=true;
                }else{
                    contador++;
                }
            }
            
            ResultadoConsultaRecursosLiterarios resultadoConsultado = new ResultadoConsultaRecursosLiterarios();
            resultadoConsultado.cargarContenido(biblioteca.getInventario().getListaRecursosLiterarios().get(contador));
            resultadoConsultado.show();
        }
        
        
    }//GEN-LAST:event_jListRecursosLiterariosMouseClicked

    private void jCheckBoxFiltroRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistaActionPerformed
        if (jCheckBoxFiltroRevista.isSelected()) {
            jCheckBoxFiltroRevistasDisponibles.setEnabled(true);
            jCheckBoxFiltroRevistasPrestadas.setEnabled(true);
            jCheckBoxFiltroRevistasVendidas.setEnabled(true);
            jComboBoxFiltroRevistaTipo.setEnabled(true);
        }else{
            jCheckBoxFiltroRevistasDisponibles.setEnabled(false);
            jCheckBoxFiltroRevistasPrestadas.setEnabled(false);
            jCheckBoxFiltroRevistasVendidas.setEnabled(false);
            jComboBoxFiltroRevistaTipo.setEnabled(false);
        }
        
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistaActionPerformed

    private void jCheckBoxFiltroLibrosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibrosDisponiblesActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibrosDisponiblesActionPerformed

    private void jComboBoxFiltroTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroTipoLibroActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jComboBoxFiltroTipoLibroActionPerformed

    private void jCheckBoxFiltroRevistasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasDisponiblesActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasDisponiblesActionPerformed

    private void jCheckBoxFiltroRevistasPrestadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasPrestadasActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasPrestadasActionPerformed

    private void jCheckBoxFiltroRevistasVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasVendidasActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasVendidasActionPerformed

    private void jComboBoxFiltroRevistaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroRevistaTipoActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jComboBoxFiltroRevistaTipoActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtEmailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailClienteKeyTyped
        // TODO add your handling code here:
        String pathRight = "/images/right.jpg";
        String pathWrong = "/images/wrong.jpg";
        String path = pathWrong;
        //URL url = this.getClass().getResource(path);
        //ImageIcon icon = new ImageIcon(url);
        ValidarDatos validacion = new ValidarDatos();
        String email = txtEmailCliente.getText();
        if(!email.equals("")){
            String validacionEmail = validacion.validarEmail(email);
            //txtErrorEmail.setText(validacionEmail);
            if(validacionEmail.equals("CORRECTO")){
                path = pathRight;
                txtErrorEmail.setText("");
                //txtErrorEmail.setIcon(icon);
            }
            else{
                path = pathWrong;
                txtErrorEmail.setText("* Ingrese email válido");
            }
            URL url = this.getClass().getResource(path);
            ImageIcon icon = new ImageIcon(url);
            txtErrorEmail.setIcon(icon);
        }
    }//GEN-LAST:event_txtEmailClienteKeyTyped

    private void txtTelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoClienteKeyTyped
        // TODO add your handling code here:
        String pathRight = "/images/right.jpg";
        String pathWrong = "/images/wrong.jpg";
        String path = pathWrong;
        //URL url = this.getClass().getResource(path);
        //ImageIcon icon = new ImageIcon(url);
        ValidarDatos validacion = new ValidarDatos();
        String telefono = txtTelefonoCliente.getText();
        if(!telefono.equals("")){
            String validacionEmail = validacion.validarTelefono(telefono);
            //txtErrorEmail.setText(validacionEmail);
            if(validacionEmail.equals("CORRECTO")){
                path = pathRight;
                txtErrorTelefono.setText("");
                //txtErrorEmail.setIcon(icon);
            }
            else{
                path = pathWrong;
                txtErrorTelefono.setText("* Ingrese email válido");
            }
            URL url = this.getClass().getResource(path);
            ImageIcon icon = new ImageIcon(url);
            txtErrorTelefono.setIcon(icon);
        }
    }//GEN-LAST:event_txtTelefonoClienteKeyTyped

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        Administrador admiCliente = new Administrador();
        String nombre = txtNombreCliente.getText();
        String email = txtEmailCliente.getText();
        String validacionEmail = admiCliente.validarEmailCliente(email);
        txtErrorEmail.setText(validacionEmail);
        String cedula = txtCedulaCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        String validacionTelefono = admiCliente.validarTelefonoCliente(telefono);
        txtErrorTelefono.setText(validacionTelefono);
        if("CORRECTO".equals(validacionEmail) && "CORRECTO".equals(validacionTelefono)){
            admiCliente.registrarCliente(nombre, cedula, email, telefono);
            refrescarPanelClientes(nombre,cedula,email,telefono);
        }

    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void refrescarPanelClientes(String nombre, String cedula, 
            String email, String telefono){
        txtErrorEmail.setForeground(Color.green);
        txtErrorTelefono.setForeground(Color.green);
        JLabel panelnombre = new javax.swing.JLabel(nombre);
        JLabel panelemail = new javax.swing.JLabel(email);
        JLabel panelcedula = new javax.swing.JLabel(cedula);
        JLabel paneltelefono = new javax.swing.JLabel(telefono);
        JButton panelMensaje = new javax.swing.JButton("ENVIAR CORREO");
        panelMensaje.setSize(25, 25);
        jPanel.setLayout(new GridLayout(0,5,20,20));
        jPanel.add(panelnombre);
        jPanel.add(panelemail);
        jPanel.add(panelcedula);
        jPanel.add(paneltelefono);
        jPanel.add(panelMensaje);
        jPanel.revalidate();
        jPanel.repaint();
        txtNombreCliente.setText("");
        txtEmailCliente.setText("");
        txtCedulaCliente.setText("");
        txtTelefonoCliente.setText("");
        txtErrorTelefono.setText(null);
        txtErrorTelefono.setIcon(null);
        txtErrorEmail.setText(null);
        txtErrorEmail.setIcon(null);
        txtErrorEmail.setForeground(Color.red);
        txtErrorTelefono.setForeground(Color.red);
    }
    
    private void refrescarjListRecursosLiterarios(){
        int contador = 0;
        DefaultListModel model = new DefaultListModel();
        while(contador<biblioteca.getInventario().getListaRecursosLiterarios().size()){
            if(jCheckBoxFiltroTodo.isSelected()){
                String s=biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId()+"      "+biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getNombre()+"     "+biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString();
                model.addElement(s);
            }else{
                if(jCheckBoxFiltroLibro.isSelected() && biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains("L-")){
                    Libro libro =(Libro) biblioteca.getInventario().getListaRecursosLiterarios().get(contador);
                    if(jComboBoxFiltroTipoLibro.getModel().getSelectedItem().toString().equalsIgnoreCase("todos")){
                        if(jCheckBoxFiltroLibrosDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.DISPONIBLE.toString())){
                            String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroLibrosPrestados.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.PRESTADO.toString())){
                            String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                            model.addElement(s);
                        }
                                     
                    }else{
                        if(jComboBoxFiltroTipoLibro.getModel().getSelectedItem().toString().equalsIgnoreCase(libro.getTipo().toString())){
                            if(jCheckBoxFiltroLibrosDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.DISPONIBLE.toString())){
                                String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroLibrosPrestados.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.PRESTADO.toString())){
                                String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                                model.addElement(s);
                            }
                        }
                    }   
                }
                
                
                if(jCheckBoxFiltroRevista.isSelected() && biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains("R-")){
                    Revista revista = (Revista) biblioteca.getInventario().getListaRecursosLiterarios().get(contador);
                    if(jComboBoxFiltroRevistaTipo.getModel().getSelectedItem().toString().equalsIgnoreCase("todas")){
                        if(jCheckBoxFiltroRevistasDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.DISPONIBLE))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroRevistasPrestadas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.PRESTADO))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroRevistasVendidas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.VENDIDO))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }
                    }else{
                        if(jComboBoxFiltroRevistaTipo.getModel().getSelectedItem().toString().equalsIgnoreCase(revista.getTipo().toString())){
                            if(jCheckBoxFiltroRevistasDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.DISPONIBLE))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroRevistasPrestadas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.PRESTADO))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroRevistasVendidas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.VENDIDO))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }
                        }
                    }
                    
                    
                }
            }
            contador++;
        }
        jListRecursosLiterarios.setModel(model);
        jListRecursosLiterarios.updateUI();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton jButtonRegistroLibro;
    private javax.swing.JButton jButtonRegistroRevista;
    private javax.swing.JCheckBox jCheckBoxFiltroLibro;
    private javax.swing.JCheckBox jCheckBoxFiltroLibrosDisponibles;
    private javax.swing.JCheckBox jCheckBoxFiltroLibrosPrestados;
    private javax.swing.JCheckBox jCheckBoxFiltroRevista;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasDisponibles;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasPrestadas;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasVendidas;
    private javax.swing.JCheckBox jCheckBoxFiltroTodo;
    private javax.swing.JComboBox<String> jComboBoxFiltroRevistaTipo;
    private javax.swing.JComboBox<String> jComboBoxFiltroTipoLibro;
    private javax.swing.JComboBox<String> jComboBoxRegistroRevistaTipo;
    private javax.swing.JComboBox<String> jComboBoxTipoLibro;
    private javax.swing.JFileChooser jFileChooserCargaRecursosLiterarios;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRecursosLiterariosFiltroLabel;
    private javax.swing.JLabel jLabelRecursosLiterariosLabel;
    private javax.swing.JLabel jLabelRegistroFiltroTipoLibro;
    private javax.swing.JLabel jLabelRegistroLibroAnio;
    private javax.swing.JLabel jLabelRegistroLibroAutor;
    private javax.swing.JLabel jLabelRegistroLibroEditorial;
    private javax.swing.JLabel jLabelRegistroLibroNombre;
    private javax.swing.JLabel jLabelRegistroLibroTipo;
    private javax.swing.JLabel jLabelRegistroLibrosTitle;
    private javax.swing.JLabel jLabelRegistroRevistaAnio;
    private javax.swing.JLabel jLabelRegistroRevistaCosto;
    private javax.swing.JLabel jLabelRegistroRevistaLabel;
    private javax.swing.JLabel jLabelRegistroRevistaNombre;
    private javax.swing.JLabel jLabelRegistroRevistaNumero;
    private javax.swing.JLabel jLabelRegistroRevistasTipo;
    private javax.swing.JLabel jLabelRegistroTipoRevista;
    private javax.swing.JList<String> jListRecursosLiterarios;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHerramientas;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemAjustes;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemImportarLiteratura;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLiteratura;
    private javax.swing.JPanel jPanelMultas;
    private javax.swing.JPanel jPanelPrestamos;
    private javax.swing.JPanel jPanelRecursoLiterarioFiltro;
    private javax.swing.JPanel jPanelRecursosLiterarios;
    private javax.swing.JPanel jPanelRegistroLibros;
    private javax.swing.JPanel jPanelRegistroRevistasLabel;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneFiltro;
    private javax.swing.JPopupMenu.Separator jSeparatorFiltro;
    private javax.swing.JSpinner jSpinnerAnioRevista;
    private javax.swing.JSpinner jSpinnerRegistroLibroAnio;
    private javax.swing.JSpinner jSpinnerRegistroRevistaCosto;
    private javax.swing.JSpinner jSpinnerRegistroRevistaNumero;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JTextField jTextFieldRegistroLibroAutor;
    private javax.swing.JTextField jTextFieldRegistroLibroEditorial;
    private javax.swing.JTextField jTextFieldRegistroLibroNombre;
    private javax.swing.JTextField jTextFieldRegistroRevistaNombre;
    private javax.swing.JLabel labelCedulaCliente;
    private javax.swing.JLabel labelCorreoCliente;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelTelefonoCliente;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JLabel txtErrorEmail;
    private javax.swing.JLabel txtErrorTelefono;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
