/*
 * Copyright (C) 2017 Bliburu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bliburu;

import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Sánchez Jiménez (jsnchzjmnz)
 * @version 0.1
 */
public class GUI extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * Asigna la biblioteca instanciada al GUI
     * @param biblioteca biblioteca que se asignará al GUI
     */
    public void setBiblioteca(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTab = new javax.swing.JTabbedPane();
        jPanelLiteratura = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListRecursosLiterarios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxFiltroLibro = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevista = new javax.swing.JCheckBox();
        jComboBoxFiltroTipoLibro = new javax.swing.JComboBox<>();
        jCheckBoxFiltroLibrosDisponibles = new javax.swing.JCheckBox();
        jCheckBoxFiltroLibrosPrestados = new javax.swing.JCheckBox();
        jCheckBoxFiltroTodo = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasDisponibles = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasPrestadas = new javax.swing.JCheckBox();
        jCheckBoxFiltroRevistasVendidas = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxFiltroRevistaTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxRegistroRevistaTipo = new javax.swing.JComboBox<>();
        jTextFieldRegistroRevistaNombre = new javax.swing.JTextField();
        jButtonRegistroRevista = new javax.swing.JButton();
        jSpinnerAnioRevista = new javax.swing.JSpinner();
        jSpinnerRegistroRevistaNumero = new javax.swing.JSpinner();
        jSpinnerRegistroRevistaCosto = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRegistroLibroNombre = new javax.swing.JTextField();
        jTextFieldRegistroLibroAutor = new javax.swing.JTextField();
        jTextFieldRegistroLibroEditorial = new javax.swing.JTextField();
        jComboBoxTipoLibro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonRegistroLibro = new javax.swing.JButton();
        jSpinnerRegistroLibroAnio = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jPanelPrestamos = new javax.swing.JPanel();
        jPanelVentas = new javax.swing.JPanel();
        jPanelClientes = new javax.swing.JPanel();
        jPanelMultas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuHerramientas = new javax.swing.JMenu();
        jMenuItemAjustes = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(170, 104, 69));
        setResizable(false);

        jTab.setBackground(new java.awt.Color(232, 232, 232));
        jTab.setBorder(null);
        jTab.setForeground(new java.awt.Color(88, 68, 49));
        jTab.setFont(new java.awt.Font("Khmer OS System", 1, 14)); // NOI18N

        jPanelLiteratura.setBackground(new java.awt.Color(232, 232, 232));

        jListRecursosLiterarios.setBackground(new java.awt.Color(232, 232, 232));
        jListRecursosLiterarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));
        jListRecursosLiterarios.setSelectionBackground(new java.awt.Color(125, 164, 203));
        jListRecursosLiterarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListRecursosLiterariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListRecursosLiterarios);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 68, 49));
        jLabel1.setText("Recursos Literarios");

        jPanel3.setBackground(new java.awt.Color(125, 164, 203));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 68, 49));
        jLabel3.setText("Filtros de Búsqueda");

        jCheckBoxFiltroLibro.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibro.setText("Libros");
        jCheckBoxFiltroLibro.setEnabled(false);
        jCheckBoxFiltroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibroActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevista.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevista.setText("Revistas");
        jCheckBoxFiltroRevista.setEnabled(false);
        jCheckBoxFiltroRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistaActionPerformed(evt);
            }
        });

        jComboBoxFiltroTipoLibro.setBackground(new java.awt.Color(125, 164, 203));
        jComboBoxFiltroTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Novela", "Teatro", "Poesía", "Ensayo", "Infantil" }));
        jComboBoxFiltroTipoLibro.setEnabled(false);
        jComboBoxFiltroTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroTipoLibroActionPerformed(evt);
            }
        });

        jCheckBoxFiltroLibrosDisponibles.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibrosDisponibles.setText("Disponibles");
        jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
        jCheckBoxFiltroLibrosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibrosDisponiblesActionPerformed(evt);
            }
        });

        jCheckBoxFiltroLibrosPrestados.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroLibrosPrestados.setText("Prestados");
        jCheckBoxFiltroLibrosPrestados.setEnabled(false);
        jCheckBoxFiltroLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroLibrosPrestadosActionPerformed(evt);
            }
        });

        jCheckBoxFiltroTodo.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroTodo.setSelected(true);
        jCheckBoxFiltroTodo.setText("Mostrar Todo");
        jCheckBoxFiltroTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroTodoActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasDisponibles.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasDisponibles.setText("Disponible");
        jCheckBoxFiltroRevistasDisponibles.setEnabled(false);
        jCheckBoxFiltroRevistasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasDisponiblesActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasPrestadas.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasPrestadas.setText("Prestado");
        jCheckBoxFiltroRevistasPrestadas.setEnabled(false);
        jCheckBoxFiltroRevistasPrestadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasPrestadasActionPerformed(evt);
            }
        });

        jCheckBoxFiltroRevistasVendidas.setBackground(new java.awt.Color(125, 164, 203));
        jCheckBoxFiltroRevistasVendidas.setText("Vendido");
        jCheckBoxFiltroRevistasVendidas.setEnabled(false);
        jCheckBoxFiltroRevistasVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroRevistasVendidasActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(125, 164, 203));
        jLabel16.setText("Tipo");

        jComboBoxFiltroRevistaTipo.setBackground(new java.awt.Color(125, 164, 203));
        jComboBoxFiltroRevistaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Venta", "Prestamo" }));
        jComboBoxFiltroRevistaTipo.setEnabled(false);
        jComboBoxFiltroRevistaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroRevistaTipoActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(125, 164, 203));
        jLabel17.setText("Tipo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFiltroTodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxFiltroLibro)
                    .addComponent(jCheckBoxFiltroRevista)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFiltroLibrosPrestados)
                                    .addComponent(jCheckBoxFiltroLibrosDisponibles)
                                    .addComponent(jComboBoxFiltroTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxFiltroRevistasPrestadas)
                                    .addComponent(jCheckBoxFiltroRevistasDisponibles)
                                    .addComponent(jCheckBoxFiltroRevistasVendidas)))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibrosDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroLibrosPrestados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxFiltroTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxFiltroRevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasPrestadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFiltroRevistasVendidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFiltroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 68, 49));
        jLabel4.setText("Registro de Revistas");

        jLabel10.setText("Nombre");

        jLabel11.setText("Número");

        jLabel12.setText("Año");

        jLabel13.setText("Costo");

        jComboBoxRegistroRevistaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Prestamo" }));

        jTextFieldRegistroRevistaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistroRevistaNombreActionPerformed(evt);
            }
        });

        jButtonRegistroRevista.setText("Registrar");
        jButtonRegistroRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroRevistaActionPerformed(evt);
            }
        });

        jSpinnerAnioRevista.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerAnioRevista.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerAnioRevista, "yyyy"));

        jSpinnerRegistroRevistaNumero.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerRegistroRevistaCosto.setModel(new javax.swing.SpinnerNumberModel(1500.0d, null, null, 1.0d));

        jLabel14.setText("Tipo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldRegistroRevistaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerRegistroRevistaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerRegistroRevistaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAnioRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jComboBoxRegistroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRegistroRevista)
                                        .addGap(55, 55, 55))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldRegistroRevistaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jSpinnerRegistroRevistaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jSpinnerRegistroRevistaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerAnioRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRegistroRevistaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRegistroRevista))))
        );

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 68, 49));
        jLabel5.setText("Registro de Libros");

        jTextFieldRegistroLibroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegistroLibroNombreActionPerformed(evt);
            }
        });

        jComboBoxTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novela", "Teatro", "Poesía", "Ensayo", "Infantil" }));

        jLabel6.setText("Nombre");

        jLabel7.setText("Autor");

        jLabel8.setText("Editorial");

        jLabel9.setText("Año");

        jButtonRegistroLibro.setText("Registrar");
        jButtonRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroLibroActionPerformed(evt);
            }
        });

        jSpinnerRegistroLibroAnio.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerRegistroLibroAnio.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerRegistroLibroAnio, "yyyy"));

        jLabel15.setText("Tipo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldRegistroLibroAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jTextFieldRegistroLibroNombre)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinnerRegistroLibroAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldRegistroLibroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 59, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jComboBoxTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRegistroLibro))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel5))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRegistroLibroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLibroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerRegistroLibroAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistroLibro))))
        );

        javax.swing.GroupLayout jPanelLiteraturaLayout = new javax.swing.GroupLayout(jPanelLiteratura);
        jPanelLiteratura.setLayout(jPanelLiteraturaLayout);
        jPanelLiteraturaLayout.setHorizontalGroup(
            jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLiteraturaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLiteraturaLayout.setVerticalGroup(
            jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLiteraturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLiteraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLiteraturaLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTab.addTab("Literatura", jPanelLiteratura);

        jPanelPrestamos.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelPrestamosLayout = new javax.swing.GroupLayout(jPanelPrestamos);
        jPanelPrestamos.setLayout(jPanelPrestamosLayout);
        jPanelPrestamosLayout.setHorizontalGroup(
            jPanelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelPrestamosLayout.setVerticalGroup(
            jPanelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Prestamos", jPanelPrestamos);

        jPanelVentas.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Ventas", jPanelVentas);

        jPanelClientes.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Clientes", jPanelClientes);

        jPanelMultas.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanelMultasLayout = new javax.swing.GroupLayout(jPanelMultas);
        jPanelMultas.setLayout(jPanelMultasLayout);
        jPanelMultasLayout.setHorizontalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanelMultasLayout.setVerticalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTab.addTab("Multas", jPanelMultas);

        jPanel2.setBackground(new java.awt.Color(125, 164, 202));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 68, 49), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItem5.setText("Importar Literatura");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem5);
        jMenuArchivo.add(jSeparator1);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItem4);

        jMenuBar.add(jMenuArchivo);

        jMenuHerramientas.setText("Herramientas");

        jMenuItemAjustes.setText("Ajustes");
        jMenuItemAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjustesActionPerformed(evt);
            }
        });
        jMenuHerramientas.add(jMenuItemAjustes);

        jMenuBar.add(jMenuHerramientas);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuItem2.setText("Acerca");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem2);

        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Acerca acerca = new Acerca();
        acerca.setTitle("About");
        acerca.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjustesActionPerformed
        Ajustes ajustes = new Ajustes();
        ajustes.setBiblioteca(biblioteca);
        ajustes.refrescarInfo();
        ajustes.show();
    }//GEN-LAST:event_jMenuItemAjustesActionPerformed

    private void jCheckBoxFiltroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibroActionPerformed
        if (jCheckBoxFiltroLibro.isSelected()) {
            jCheckBoxFiltroLibrosDisponibles.setEnabled(true);
            jCheckBoxFiltroLibrosPrestados.setEnabled(true);
            jComboBoxFiltroTipoLibro.setEnabled(true);
        }else{
            jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
            jCheckBoxFiltroLibrosPrestados.setEnabled(false);
            jComboBoxFiltroTipoLibro.setEnabled(false);
        }
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibroActionPerformed

    private void jTextFieldRegistroLibroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistroLibroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistroLibroNombreActionPerformed

    private void jTextFieldRegistroRevistaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegistroRevistaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegistroRevistaNombreActionPerformed

    private void jButtonRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroLibroActionPerformed

        biblioteca.getInventario().registrarLibro(jTextFieldRegistroLibroNombre.getText(), jTextFieldRegistroLibroAutor.getText(), (Date) jSpinnerRegistroLibroAnio.getModel().getValue(),jTextFieldRegistroLibroEditorial.getText(), TipoLibro.valueOf(jComboBoxTipoLibro.getModel().getSelectedItem().toString().toUpperCase()));
        refrescarjListRecursosLiterarios();
        
    }//GEN-LAST:event_jButtonRegistroLibroActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        String ruta = jFileChooser1.getSelectedFile().getAbsolutePath();
            try {
                biblioteca.getInventario().registroAutomatico(ruta);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            refrescarjListRecursosLiterarios();
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButtonRegistroRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroRevistaActionPerformed
        biblioteca.getInventario().registrarRevista(jTextFieldRegistroRevistaNombre.getText(), (int) jSpinnerRegistroRevistaNumero.getModel().getValue(), (Date) jSpinnerAnioRevista.getValue(), TipoRevista.valueOf(jComboBoxRegistroRevistaTipo.getModel().getSelectedItem().toString().toUpperCase()), (double) jSpinnerRegistroRevistaCosto.getValue());
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jButtonRegistroRevistaActionPerformed

    private void jCheckBoxFiltroTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroTodoActionPerformed
        if(jCheckBoxFiltroTodo.isSelected()){
            jCheckBoxFiltroLibro.setEnabled(false);
            jCheckBoxFiltroRevista.setEnabled(false);
            jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
            jCheckBoxFiltroLibrosPrestados.setEnabled(false);
            jComboBoxFiltroTipoLibro.setEnabled(false);
            
            
        }else{
            jCheckBoxFiltroLibro.setEnabled(true);
            jCheckBoxFiltroRevista.setEnabled(true);
            if(jCheckBoxFiltroLibro.isSelected()){
                jCheckBoxFiltroLibrosDisponibles.setEnabled(true);
                jCheckBoxFiltroLibrosPrestados.setEnabled(true);
                jComboBoxFiltroTipoLibro.setEnabled(true);
            }else{
                jCheckBoxFiltroLibrosDisponibles.setEnabled(false);
                jCheckBoxFiltroLibrosPrestados.setEnabled(false);
                jComboBoxFiltroTipoLibro.setEnabled(false);
            }
            
           
        }
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroTodoActionPerformed

    private void jCheckBoxFiltroLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibrosPrestadosActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibrosPrestadosActionPerformed

    private void jListRecursosLiterariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRecursosLiterariosMouseClicked
        
        if(jListRecursosLiterarios.getModel().getSize()>0){
 
            String id= jListRecursosLiterarios.getSelectedValue().split(" ")[0];
            int contador=0;
            boolean flag=false;
            while(contador<biblioteca.getInventario().getListaRecursosLiterarios().size() && !flag){
                if(biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains(id)){
                    flag=true;
                }else{
                    contador++;
                }
            }
            
            ResultadoConsultaRecursosLiterarios resultadoConsultado = new ResultadoConsultaRecursosLiterarios();
            resultadoConsultado.cargarContenido(biblioteca.getInventario().getListaRecursosLiterarios().get(contador));
            resultadoConsultado.show();
        }
        
        
    }//GEN-LAST:event_jListRecursosLiterariosMouseClicked

    private void jCheckBoxFiltroRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistaActionPerformed
        if (jCheckBoxFiltroRevista.isSelected()) {
            jCheckBoxFiltroRevistasDisponibles.setEnabled(true);
            jCheckBoxFiltroRevistasPrestadas.setEnabled(true);
            jCheckBoxFiltroRevistasVendidas.setEnabled(true);
            jComboBoxFiltroRevistaTipo.setEnabled(true);
        }else{
            jCheckBoxFiltroRevistasDisponibles.setEnabled(false);
            jCheckBoxFiltroRevistasPrestadas.setEnabled(false);
            jCheckBoxFiltroRevistasVendidas.setEnabled(false);
            jComboBoxFiltroRevistaTipo.setEnabled(false);
        }
        
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistaActionPerformed

    private void jCheckBoxFiltroLibrosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroLibrosDisponiblesActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroLibrosDisponiblesActionPerformed

    private void jComboBoxFiltroTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroTipoLibroActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jComboBoxFiltroTipoLibroActionPerformed

    private void jCheckBoxFiltroRevistasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasDisponiblesActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasDisponiblesActionPerformed

    private void jCheckBoxFiltroRevistasPrestadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasPrestadasActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasPrestadasActionPerformed

    private void jCheckBoxFiltroRevistasVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroRevistasVendidasActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jCheckBoxFiltroRevistasVendidasActionPerformed

    private void jComboBoxFiltroRevistaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroRevistaTipoActionPerformed
        refrescarjListRecursosLiterarios();
    }//GEN-LAST:event_jComboBoxFiltroRevistaTipoActionPerformed

    
    private void refrescarjListRecursosLiterarios(){
        int contador = 0;
        DefaultListModel model = new DefaultListModel();
        while(contador<biblioteca.getInventario().getListaRecursosLiterarios().size()){
            if(jCheckBoxFiltroTodo.isSelected()){
                String s=biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId()+"      "+biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getNombre()+"     "+biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString();
                model.addElement(s);
            }else{
                if(jCheckBoxFiltroLibro.isSelected() && biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains("L-")){
                    Libro libro =(Libro) biblioteca.getInventario().getListaRecursosLiterarios().get(contador);
                    if(jComboBoxFiltroTipoLibro.getModel().getSelectedItem().toString().equalsIgnoreCase("todos")){
                        if(jCheckBoxFiltroLibrosDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.DISPONIBLE.toString())){
                            String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroLibrosPrestados.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.PRESTADO.toString())){
                            String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                            model.addElement(s);
                        }
                                     
                    }else{
                        if(jComboBoxFiltroTipoLibro.getModel().getSelectedItem().toString().equalsIgnoreCase(libro.getTipo().toString())){
                            if(jCheckBoxFiltroLibrosDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.DISPONIBLE.toString())){
                                String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroLibrosPrestados.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().toString()==Estado.PRESTADO.toString())){
                                String s=libro.getId()+"    "+libro.getNombre()+"    "+libro.getEstado();
                                model.addElement(s);
                            }
                        }
                    }   
                }
                
                
                if(jCheckBoxFiltroRevista.isSelected() && biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getId().contains("R-")){
                    Revista revista = (Revista) biblioteca.getInventario().getListaRecursosLiterarios().get(contador);
                    if(jComboBoxFiltroRevistaTipo.getModel().getSelectedItem().toString().equalsIgnoreCase("todas")){
                        if(jCheckBoxFiltroRevistasDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.DISPONIBLE))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroRevistasPrestadas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.PRESTADO))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }else if(jCheckBoxFiltroRevistasVendidas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.VENDIDO))){
                            String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                            model.addElement(s);
                        }
                    }else{
                        if(jComboBoxFiltroRevistaTipo.getModel().getSelectedItem().toString().equalsIgnoreCase(revista.getTipo().toString())){
                            if(jCheckBoxFiltroRevistasDisponibles.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.DISPONIBLE))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroRevistasPrestadas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.PRESTADO))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }else if(jCheckBoxFiltroRevistasVendidas.isSelected() && (biblioteca.getInventario().getListaRecursosLiterarios().get(contador).getEstado().equals(Estado.VENDIDO))){
                                String s=revista.getId()+"    "+revista.getNombre()+"    "+revista.getEstado();
                                model.addElement(s);
                            }
                        }
                    }
                    
                    
                }
            }
            contador++;
        }
        jListRecursosLiterarios.setModel(model);
        jListRecursosLiterarios.updateUI();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistroLibro;
    private javax.swing.JButton jButtonRegistroRevista;
    private javax.swing.JCheckBox jCheckBoxFiltroLibro;
    private javax.swing.JCheckBox jCheckBoxFiltroLibrosDisponibles;
    private javax.swing.JCheckBox jCheckBoxFiltroLibrosPrestados;
    private javax.swing.JCheckBox jCheckBoxFiltroRevista;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasDisponibles;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasPrestadas;
    private javax.swing.JCheckBox jCheckBoxFiltroRevistasVendidas;
    private javax.swing.JCheckBox jCheckBoxFiltroTodo;
    private javax.swing.JComboBox<String> jComboBoxFiltroRevistaTipo;
    private javax.swing.JComboBox<String> jComboBoxFiltroTipoLibro;
    private javax.swing.JComboBox<String> jComboBoxRegistroRevistaTipo;
    private javax.swing.JComboBox<String> jComboBoxTipoLibro;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListRecursosLiterarios;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHerramientas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAjustes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelLiteratura;
    private javax.swing.JPanel jPanelMultas;
    private javax.swing.JPanel jPanelPrestamos;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerAnioRevista;
    private javax.swing.JSpinner jSpinnerRegistroLibroAnio;
    private javax.swing.JSpinner jSpinnerRegistroRevistaCosto;
    private javax.swing.JSpinner jSpinnerRegistroRevistaNumero;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JTextField jTextFieldRegistroLibroAutor;
    private javax.swing.JTextField jTextFieldRegistroLibroEditorial;
    private javax.swing.JTextField jTextFieldRegistroLibroNombre;
    private javax.swing.JTextField jTextFieldRegistroRevistaNombre;
    // End of variables declaration//GEN-END:variables
}
