/*
 * Copyright (C) 2017 julio
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bliburu;

import java.util.Calendar;

/**
 *
 * @author julio
 */
public class ResultadoConsultaRecursosLiterarios extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoConsultaRecursosLiterarios
     */
    public ResultadoConsultaRecursosLiterarios() {
        initComponents();
    }

    public void cargarContenido(RecursoLiterario recurso){
        if(recurso.getId().contains("L-")){
            Libro libro = (Libro)recurso;
            jLabelTitulo.setText("Información del Libro");
            jLabelNombreValor.setText(libro.getNombre());
            jLabelIDValor.setText(libro.getId());
            jLabelAnioValor.setText(recurso.getAnio().toString());
            jLabelAutorNumero.setText("Autor: ");
            jLabelAutorNumeroValor.setText(libro.getAutor());
            jLabelEditorialTipo.setText("Editorial: ");
            jLabelEditorialTipoValor.setText(libro.getEditorial());
            jLabelTipoCosto.setText("Tipo: ");
            jLabelTipoCostoValor.setText(libro.getTipo().toString());
            jLabelEstadoValor.setText(libro.getEstado().toString());
        }else if(recurso.getId().contains("R-")){
            Revista revista = (Revista)recurso;
            jLabelTitulo.setText("Información de la Revista");
            jLabelNombreValor.setText(revista.getNombre());
            jLabelIDValor.setText(revista.getId());
            jLabelAnioValor.setText(Integer.toString(recurso.getAnio().getYear()));
            jLabelAutorNumero.setText("Número: ");
            jLabelAutorNumeroValor.setText(Integer.toString(revista.getNumero()));
            jLabelEditorialTipo.setText("Tipo: ");
            jLabelEditorialTipoValor.setText(revista.getTipo().toString());
            jLabelTipoCosto.setText("Costo: ");
            jLabelTipoCostoValor.setText(Double.toString(revista.getCosto()));
            jLabelEstadoValor.setText(revista.getEstado().toString());
        }else{
            jLabelTitulo.setText("Se ha producido un error");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabelAutorNumero = new javax.swing.JLabel();
        jLabelEditorialTipo = new javax.swing.JLabel();
        jLabelTipoCosto = new javax.swing.JLabel();
        jLabelNombreValor = new javax.swing.JLabel();
        jLabelIDValor = new javax.swing.JLabel();
        jLabelAnioValor = new javax.swing.JLabel();
        jLabelAutorNumeroValor = new javax.swing.JLabel();
        jLabelEditorialTipoValor = new javax.swing.JLabel();
        jLabelTipoCostoValor = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelEstadoValor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(232, 232, 232));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        jLabelTitulo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabelTitulo.setText("Información del Recurso Literario");

        jLabelNombre.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelID.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelID.setText("ID:");

        jLabelAnio.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelAnio.setText("Año:");

        jLabelAutorNumero.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelAutorNumero.setText("jLabel3");

        jLabelEditorialTipo.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelEditorialTipo.setText("jLabel1");

        jLabelTipoCosto.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelTipoCosto.setText("jLabel1");

        jLabelNombreValor.setText("Nombre:");

        jLabelIDValor.setText("ID:");

        jLabelAnioValor.setText("Año:");

        jLabelAutorNumeroValor.setText("jLabel3");

        jLabelEditorialTipoValor.setText("jLabel1");

        jLabelTipoCostoValor.setText("jLabel1");

        jLabelEstado.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelEstado.setText("Estado: ");

        jLabelCliente.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabelCliente.setText("Información del Cliente:");

        jLabelEstadoValor.setText("jLabel1");

        jPanel3.setBackground(new java.awt.Color(232, 232, 232));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelEditorialTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEditorialTipoValor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNombreValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelIDValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAnio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAnioValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAutorNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelAutorNumeroValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTipoCosto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTipoCostoValor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEstadoValor))
                            .addComponent(jLabelCliente)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelNombreValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jLabelIDValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnio)
                    .addComponent(jLabelAnioValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorNumero)
                    .addComponent(jLabelAutorNumeroValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditorialTipo)
                    .addComponent(jLabelEditorialTipoValor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoCosto)
                    .addComponent(jLabelTipoCostoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabelEstadoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoConsultaRecursosLiterarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoConsultaRecursosLiterarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoConsultaRecursosLiterarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoConsultaRecursosLiterarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoConsultaRecursosLiterarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelAnioValor;
    private javax.swing.JLabel jLabelAutorNumero;
    private javax.swing.JLabel jLabelAutorNumeroValor;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelEditorialTipo;
    private javax.swing.JLabel jLabelEditorialTipoValor;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoValor;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDValor;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreValor;
    private javax.swing.JLabel jLabelTipoCosto;
    private javax.swing.JLabel jLabelTipoCostoValor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
